= Cahier des charges utilisateurs V2 : Projet DailyBank

:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe:  

.Groupe 4B01, Auteur : Maxime Planquès, publié le 16/05/2023
Créé pour : Détailler la version 2 du projet DailyBank




== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour tester les différentes fonctionnalités de cette dernière.


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

