= Cahier De Recette - DailyBankApp
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe:  

.Créé par : Mathis Brefuel
Créé pour : Tester les fonctionnalités de l'application

 



== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour tester les différentes fonctionnalités de cette dernière.


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK


5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK

|====


==== 1.2 Gestion des comptes bancaires :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Création d'un compte
>|Objectif 4+| Créer un compte courant pour un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.3 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.4 ^|Sélectionner le bouton "Nouveau Compte". ^|La page des informations sur le nouveau compte s’affiche. ^|La fenêtre s'ouvre ^|OK
^|All_G_CB.5 ^|Sélectionner le bouton "Ajouter". ^|La page des gestions des comptes s’affiche. ^|Le nouveau compte est ajouté ^|OK

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Modifier d'un compte
>|Objectif 4+| Modifier un compte courant pour un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.6 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.7 ^|Sélectionner le bouton "Nouveau compte". ^|La page des informations sur le compte sélectionné s’affiche. ^|La fenêtre s'ouvre ^|OK
^|All_G_CB.8 ^|Sélectionner le bouton "Modifier". ^|La page des gestions des comptes s’affiche. ^|Le compte sélectionné est modifié ^|OK

|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Clôturer un compte
>|Objectif 4+| Clôturer le compte courant d'un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.6 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.7 ^|Sélectionner le bouton "Supprimer compte". ^|La page des gestions des comptes s'affiche sans le compte clôturer, mais il reste dans la BD. ^|La fenêtre s'ouvre ^|OK
*

|====


==== 1.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.5 ^|Cliquer sur le bouton "Enregistrer Crédit". ^|La page des crédits du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.6  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +150 euros
 ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Virement compte à compte
>|Objectif 4+| Effectuer un virement d'un compte à un autre

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.7 ^|Cliquer sur le bouton "Virement". ^|La page du virement du compte s’affiche. ^| La fenêtre de la gestion du virement s'ouvre ^|OK
^|All_G_COP.8  ^|Rentrer un numéro de compte dans le premier champ ("Débiteur"). ^|Le numéro de compte est bien rentré ^| Le numéro doit correspondre
 ^|OK
^|All_G_COP.9  ^|Rentrer un numéro de compte dans le premier champ ("Créditeur"). ^|Le numéro de compte est bien rentré ^| Le numéro doit correspondre
^|OK
^|All_G_COP.10  ^|Rentrer un montant dans le champ Montant. ^|Le nouveau solde du créditeur a augmenté celui du débiteur a baissé ^| Le montant doit prendre en compte le découvert du débiteur
^|OK
  
 
|====






=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...


|====

==== 2.2 Gestion des employés :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Création d'un employé
>|Objectif 4+| Vérification de la création d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.1 ^|Cliquer sur le bouton "Nouveau employé". ^|La fenêtre de création des employés s'ouvre. ^| aucune ^|OK
^|All_G_E.2 ^|Compléter les champs spécifiés et valider. ^|Un nouvel employé est créé. ^|aucune ^|OK

 
|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+|Modification d'un employé
>|Objectif 4+| Vérification de la modification d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.1 ^|Cliquer sur le bouton "Modifier employé". ^|La fenêtre de modification des employés s'ouvre. ^| Ouverture de la fenêtre ^|OK
^|All_G_E.2 ^|Compléter les champs spécifiés et valider. ^|L'employé selectionné est modifié. ^|aucune ^|OK

 
|====

|====

>|Cas de test 4+|Test-02-02-03
>|Titre 4+|Suppression d'un employé
>|Objectif 4+| Vérification de la suppression d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.1 ^|Cliquer sur le bouton "Supprimer employé". ^|La fenêtre de la liste des employés s'ouvre sans l'employé sélectionné. ^| aucune ^|OK
 
|====


